# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbuser',
            options={'managed': True},
        ),
    ]
