# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160303_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbuser',
            options={'managed': True, 'permissions': (('can_view', 'Can see available tasks'), ('can_change_status', 'Can change the status of tasks'), ('can_close', 'Can remove a task by setting its status as closed'))},
        ),
    ]
