# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160303_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbuser',
            options={'managed': True, 'permissions': (('view_task', 'Can see available tasks'), ('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed'))},
        ),
    ]
