# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160307_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbuser',
            options={'managed': True},
        ),
    ]
